### ISSUE TITLE
Cannot pickle dataset?

### ISSUE THREAD

**Issue by 252057052** [Justin1904/Low-rank-Multimodal-Fusion#15]
Can't pickle local object 'load_mosi.<locals>.MOSI'

**Comment by frallisland** [comment]
you maybe download dataset firdt.

**Comment by Justin1904** [comment]
Can you provide more context? Like the full stack trace and where you download and put the data?

**Comment by Junge718** [comment]
like this:
Traceback (most recent call last):
  File "train_mosi.py", line 264, in <module>
    main(PARAMS)
  File "train_mosi.py", line 131, in main
    for batch in train_iterator:
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'load_mosi.<locals>.MOSI'

**Comment by Justin1904** [comment]
This looks weird, seems like the error is coming from inside the torch dataloader? Which version of pytorch is this

**Comment by Junge718** [comment]
> This looks weird, seems like the error is coming from inside the torch dataloader? Which version of pytorch is this

It's 1.7.1. Maybe it's just because my OS is Windows.

**Comment by elmliu** [comment]
```train_iterator = DataLoader(train_set, batch_size=batch_sz, num_workers=0, shuffle=True)```
Works for me on Windows after changing ```num_workers=4``` to ```0```. This is probably because multiprocessing lib doesn’t have it implemented on Windows.

**Comment by Weiyinyin11** [comment]
> > This looks weird, seems like the error is coming from inside the torch dataloader? Which version of pytorch is this
> 
> It's 1.7.1. Maybe it's just because my OS is Windows.

Has your problem been solved?

**Comment by Junge718** [comment]
Thank you very much for your attention to my problem. I have tried on Linux and there are no problems on Linux. But I still can't run the code on Windows.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Justin1904/Low-rank-Multimodal-Fusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 晚上9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Justin1904/Low-rank-Multimodal-Fusion] Cannot pickle dataset? (#15)





   
This looks weird, seems like the error is coming from inside the torch dataloader? Which version of pytorch is this
  
It's 1.7.1. Maybe it's just because my OS is Windows.
  
Has your problem been solved?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Weiyinyin11** [comment]
> 非常感谢您对我的问题的关注。我在 Linux 上试过，在 Linux 上没有问题。但是我仍然无法在 Windows 上运行代码。 
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Justin1904/Low-rank-Multimodal-Fusion" ***@***.***&gt;; 发送时间:&nbsp;2021年12月1日(星期三) 晚上9:12 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Justin1904/Low-rank-Multimodal-Fusion] Cannot pickle dataset? (#15) This looks weird, seems like the error is coming from inside the torch dataloader? Which version of pytorch is this It's 1.7.1. Maybe it's just because my OS is Windows. Has your problem been solved? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Thank you for your reply. Is it convenient to leave a contact information?May I ask you some questions?
